"""
Identity — Human Sovereign Key Ceremony

The HumanIdentity class manages the cryptographic identity that anchors
the entire OBLISK architecture. The master key is derived from user input
plus optional biometric data. 

Principle: No cloud backup. No recovery. The human IS the key.
"""

from __future__ import annotations

import secrets
import hashlib
from pathlib import Path
from typing import Optional
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives.kdf.hkdf import HKDF
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import ed25519


class HumanIdentity:
    """
    Represents a human's sovereign cryptographic identity within OBLISK.
    
    This identity is the root of trust. All intents are signed by this identity,
    all policies are encrypted under its keys, and all agent actions are
    authorized through its vault.
    
    Attributes:
        master_key: The 256-bit master key derived from passphrase + biometric
        signing_key: Ed25519 private key derived from master key
        verifying_key: Ed25519 public key for intent verification
        identity_hash: Public identity fingerprint (safe to share)
    """
    
    def __init__(self, master_key: bytes):
        """
        Initialize identity from an existing master key.
        
        Use HumanIdentity.from_passphrase() or from_ceremony() for new identities.
        """
        if len(master_key) != 32:
            raise ValueError("Master key must be 32 bytes (256 bits)")
        
        self.master_key = master_key
        
        # Derive signing key deterministically from master key
        signing_seed = hashlib.sha256(master_key + b"oblisk.signing").digest()[:32]
        self._signing_key = ed25519.Ed25519PrivateKey.from_private_bytes(signing_seed)
        self.verifying_key = self._signing_key.public_key()
        
        # Public identity hash — safe to share, used for agent binding
        self.identity_hash = hashlib.sha256(
            self.verifying_key.public_bytes_raw()
        ).hexdigest()[:32]
    
    @classmethod
    def from_passphrase(
        cls, 
        passphrase: str, 
        salt: Optional[bytes] = None
    ) -> "HumanIdentity":
        """
        Generate sovereign keys from a user passphrase.
        
        This is the primary entry point for identity creation. The passphrase
        should be high-entropy (generated by the key ceremony, not user-chosen).
        
        Args:
            passphrase: High-entropy passphrase from the ceremony
            salt: Optional additional salt (e.g., from biometric data)
            
        Returns:
            A new HumanIdentity instance
        """
        # Combine passphrase with optional biometric salt
        combined = passphrase.encode("utf-8")
        if salt:
            combined = salt + combined
        
        # Derive master key with high iteration count
        kdf = PBKDF2HMAC(
            algorithm=hashes.SHA256(),
            length=32,
            salt=hashlib.sha256(b"oblisk.identity" + (salt or b"")).digest()[:16],
            iterations=600_000,
        )
        master_key = kdf.derive(combined)
        
        return cls(master_key)
    
    @classmethod
    def from_ceremony(
        cls,
        passphrase: str,
        biometric_salt: Optional[bytes] = None,
        ceremony_proof: Optional[dict] = None
    ) -> "HumanIdentity":
        """
        Create identity from the full key generation ceremony.
        
        The ceremony is a ritualized process that ensures the human
        understands they ARE the key — there is no backup, no cloud recovery.
        
        Args:
            passphrase: High-entropy passphrase
            biometric_salt: Optional biometric-derived salt
            ceremony_proof: Proof that the ceremony was completed
            
        Returns:
            HumanIdentity + ceremony attestation
        """
        identity = cls.from_passphrase(passphrase, biometric_salt)
        
        # Generate ceremony attestation
        attestation = {
            "identity_hash": identity.identity_hash,
            "ceremony_version": "2.0.0",
            "biometric_enrolled": biometric_salt is not None,
            "timestamp": None,  # Set by caller with secure timestamp
            "proof": ceremony_proof or {},
        }
        
        return identity, attestation
    
    def sign_intent(self, intent: dict) -> bytes:
        """
        Cryptographically sign an intent.
        
        The signature binds the intent to this human identity, creating
        a non-repudiable record that this specific human authorized this intent.
        
        Args:
            intent: The intent dictionary to sign
            
        Returns:
            Ed25519 signature bytes
        """
        intent_bytes = str(intent).encode("utf-8")
        return self._signing_key.sign(intent_bytes)
    
    def verify_intent(self, intent: dict, signature: bytes) -> bool:
        """
        Verify an intent signature.
        
        Used by the FlowController to confirm an intent was genuinely
        signed by this identity before authorizing agent action.
        """
        intent_bytes = str(intent).encode("utf-8")
        try:
            self.verifying_key.verify(signature, intent_bytes)
            return True
        except Exception:
            return False
    
    def derive_agent_key(self, agent_id: str) -> bytes:
        """
        Derive a unique key for a specific agent.
        
        Each agent gets its own derived key, so agents cannot decrypt
        each other's communications or access each other's data.
        
        Args:
            agent_id: The unique agent identifier
            
        Returns:
            32-byte derived key
        """
        hkdf = HKDF(
            algorithm=hashes.SHA256(),
            length=32,
            salt=None,
            info=f"oblisk.agent.{agent_id}".encode(),
        )
        return hkdf.derive(self.master_key)
