"""
Exfiltration Detector — Behavioral Analysis

The ExfiltrationDetector performs behavioral analysis on agents to
detect if they're attempting to "phone home" — leak data through
covert channels, timing attacks, or unexpected network behavior.

Principle: An agent that tries to hide its communications is compromised.
"""

from __future__ import annotations

import time
from typing import Optional
from dataclasses import dataclass, field
from enum import Enum
from collections import defaultdict


class AlertLevel(Enum):
    """Severity levels for exfiltration alerts."""
    NORMAL = "normal"
    SUSPICIOUS = "suspicious"
    HIGH_RISK = "high_risk"
    CRITICAL = "critical"


@dataclass
class BehaviorProfile:
    """
    Behavioral profile for a single agent.
    
    Tracks network patterns, data access, and timing to establish
    a baseline of normal behavior. Deviations trigger alerts.
    
    Attributes:
        agent_id: The agent being profiled
        request_times: Timestamps of network requests
        destinations: Unique destinations contacted
        data_volume: Estimated data volume sent
        pattern_score: Anomaly score (0-1, higher = more suspicious)
        created_at: When the profile was created
    """
    agent_id: str
    request_times: list[float] = field(default_factory=list)
    destinations: set[str] = field(default_factory=set)
    data_volume: int = 0
    pattern_score: float = 0.0
    created_at: float = field(default_factory=time.time)
    
    @property
    def request_rate(self) -> float:
        """Requests per minute over the last 5 minutes."""
        cutoff = time.time() - 300
        recent = [t for t in self.request_times if t > cutoff]
        if not recent:
            return 0.0
        return len(recent) / 5.0
    
    @property
    def destination_diversity(self) -> int:
        """Number of unique destinations contacted."""
        return len(self.destinations)


@dataclass
class ExfiltrationAlert:
    """
    An alert generated by the exfiltration detector.
    
    Attributes:
        alert_id: Unique identifier
        agent_id: Which agent triggered the alert
        level: Severity
        indicator: What behavior triggered the alert
        details: Human-readable explanation
        timestamp: When the alert was generated
    """
    alert_id: str
    agent_id: str
    level: AlertLevel
    indicator: str
    details: str
    timestamp: float = field(default_factory=time.time)


class ExfiltrationDetector:
    """
    Behavioral analysis system for detecting data exfiltration.
    
    The ExfiltrationDetector monitors agent behavior over time and
    flags suspicious patterns that might indicate covert data leakage.
    
    Detected patterns:
        - Timing channels (requests at regular intervals)
        - Volume anomalies (sudden spikes in data transfer)
        - Destination anomalies (contacting unexpected endpoints)
        - Request rate anomalies (too many requests too fast)
        - Covert channels (steganography in request parameters)
    
    Attributes:
        profiles: Behavioral profiles per agent
        alert_history: All generated alerts
    """
    
    # Thresholds for anomaly detection
    MAX_REQUEST_RATE = 30  # requests per minute
    MAX_DESTINATIONS = 5   # unique destinations per hour
    MAX_DATA_VOLUME = 1024 * 1024  # 1MB per hour
    TIMING_REGULARITY_THRESHOLD = 0.9  # correlation coefficient
    
    def __init__(self):
        self.profiles: dict[str, BehaviorProfile] = {}
        self.alert_history: list[ExfiltrationAlert] = []
        self._alert_counter: int = 0
    
    def record_request(
        self, 
        agent_id: str, 
        destination: str, 
        data_size: int = 0
    ) -> Optional[ExfiltrationAlert]:
        """
        Record a network request from an agent and check for anomalies.
        
        This should be called by the agent runtime for every outbound request.
        
        Args:
            agent_id: Which agent made the request
            destination: The endpoint contacted
            data_size: Estimated size of data sent
            
        Returns:
            Alert if anomaly detected, None if normal
        """
        # Get or create profile
        profile = self.profiles.get(agent_id)
        if profile is None:
            profile = BehaviorProfile(agent_id=agent_id)
            self.profiles[agent_id] = profile
        
        # Update profile
        now = time.time()
        profile.request_times.append(now)
        profile.destinations.add(destination)
        profile.data_volume += data_size
        
        # Check for anomalies
        alert = self._check_anomalies(agent_id, profile, destination, data_size)
        if alert:
            self.alert_history.append(alert)
        
        return alert
    
    def _check_anomalies(
        self, 
        agent_id: str, 
        profile: BehaviorProfile,
        destination: str,
        data_size: int
    ) -> Optional[ExfiltrationAlert]:
        """Check profile for anomalous behavior patterns."""
        
        # Check request rate
        if profile.request_rate > self.MAX_REQUEST_RATE:
            return self._create_alert(
                agent_id, AlertLevel.CRITICAL,
                "request_rate_anomaly",
                f"Agent {agent_id} making {profile.request_rate:.1f} req/min "
                f"(limit: {self.MAX_REQUEST_RATE})"
            )
        
        # Check destination diversity
        if profile.destination_diversity > self.MAX_DESTINATIONS:
            return self._create_alert(
                agent_id, AlertLevel.HIGH_RISK,
                "destination_diversity_anomaly",
                f"Agent {agent_id} contacted {profile.destination_diversity} unique "
                f"destinations (limit: {self.MAX_DESTINATIONS})"
            )
        
        # Check data volume
        hourly_volume = self._get_hourly_volume(agent_id)
        if hourly_volume > self.MAX_DATA_VOLUME:
            return self._create_alert(
                agent_id, AlertLevel.HIGH_RISK,
                "data_volume_anomaly",
                f"Agent {agent_id} transferred {hourly_volume / 1024:.1f}KB in the "
                f"last hour (limit: {self.MAX_DATA_VOLUME / 1024:.1f}KB)"
            )
        
        # Check timing regularity (potential timing channel)
        if len(profile.request_times) >= 10:
            regularity = self._calculate_timing_regularity(profile.request_times)
            if regularity > self.TIMING_REGULARITY_THRESHOLD:
                return self._create_alert(
                    agent_id, AlertLevel.SUSPICIOUS,
                    "timing_channel_suspected",
                    f"Agent {agent_id} requests show {regularity:.2f} regularity "
                    f"(possible timing channel, threshold: {self.TIMING_REGULARITY_THRESHOLD})"
                )
        
        return None
    
    def _create_alert(
        self, 
        agent_id: str, 
        level: AlertLevel, 
        indicator: str, 
        details: str
    ) -> ExfiltrationAlert:
        """Create a new exfiltration alert."""
        self._alert_counter += 1
        return ExfiltrationAlert(
            alert_id=f"EXFIL_{self._alert_counter:04d}",
            agent_id=agent_id,
            level=level,
            indicator=indicator,
            details=details,
        )
    
    def _get_hourly_volume(self, agent_id: str) -> int:
        """Get data volume for the last hour."""
        # In production, this would query a time-series database
        profile = self.profiles.get(agent_id)
        if profile is None:
            return 0
        return profile.data_volume  # Simplified
    
    def _calculate_timing_regularity(self, times: list[float]) -> float:
        """
        Calculate how regular the timing between requests is.
        
        High regularity (close to 1.0) suggests a timing channel,
        where data is encoded in the timing of requests.
        """
        if len(times) < 2:
            return 0.0
        
        # Calculate intervals
        intervals = [times[i] - times[i-1] for i in range(1, len(times))]
        
        if len(intervals) < 2:
            return 0.0
        
        # Calculate coefficient of variation (lower = more regular)
        import statistics
        try:
            mean = statistics.mean(intervals)
            stdev = statistics.stdev(intervals)
            if mean == 0:
                return 1.0
            cv = stdev / mean
            # Convert to regularity score (1.0 = perfectly regular)
            regularity = max(0.0, 1.0 - cv)
            return regularity
        except statistics.StatisticsError:
            return 0.0
    
    def get_profile(self, agent_id: str) -> Optional[BehaviorProfile]:
        """Get the behavioral profile for an agent."""
        return self.profiles.get(agent_id)
    
    def get_alerts(
        self, 
        agent_id: Optional[str] = None, 
        min_level: Optional[AlertLevel] = None
    ) -> list[ExfiltrationAlert]:
        """
        Get alerts, optionally filtered by agent and severity.
        
        Args:
            agent_id: Filter to specific agent
            min_level: Minimum severity level
            
        Returns:
            List of matching alerts
        """
        alerts = self.alert_history
        
        if agent_id:
            alerts = [a for a in alerts if a.agent_id == agent_id]
        
        if min_level:
            level_order = {
                AlertLevel.NORMAL: 0,
                AlertLevel.SUSPICIOUS: 1,
                AlertLevel.HIGH_RISK: 2,
                AlertLevel.CRITICAL: 3,
            }
            min_val = level_order[min_level]
            alerts = [a for a in alerts if level_order[a.level] >= min_val]
        
        return alerts
    
    def get_risk_score(self, agent_id: str) -> float:
        """
        Calculate an overall risk score for an agent (0-1).
        
        Higher scores indicate more suspicious behavior.
        """
        profile = self.profiles.get(agent_id)
        if profile is None:
            return 0.0
        
        alerts = self.get_alerts(agent_id)
        if not alerts:
            return 0.0
        
        # Weight by alert severity
        level_weights = {
            AlertLevel.NORMAL: 0.1,
            AlertLevel.SUSPICIOUS: 0.3,
            AlertLevel.HIGH_RISK: 0.6,
            AlertLevel.CRITICAL: 1.0,
        }
        
        total_weight = sum(level_weights[a.level] for a in alerts)
        score = min(1.0, total_weight / 3.0)  # Cap at 1.0, normalize
        
        return score
